"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function OnboardingPage() {
  const router = useRouter();

    const [fullName, setFullName] = useState("");
      const [bio, setBio] = useState("");
        const [website, setWebsite] = useState("");
          const [loading, setLoading] = useState(false);
            const [error, setError] = useState("");

              const handleSubmit = async (e: React.FormEvent) => {
                  e.preventDefault();
                      setError("");
                          setLoading(true);

                              const {
                                    data: { user },
                                          error: userError,
                                              } = await supabase.auth.getUser();

                                                  if (userError || !user) {
                                                        setError("Not authenticated. Please sign in again.");
                                                              setLoading(false);
                                                                    return;
                                                                        }

                                                                            const { error: insertError } = await supabase
                                                                                  .from("profiles")
                                                                                        .upsert({
                                                                                                id: user.id,
                                                                                                        full_name: fullName,
                                                                                                                bio,
                                                                                                                        website,
                                                                                                                              });

                                                                                                                                  if (insertError) {
                                                                                                                                        setError("Failed to save profile. Please try again.");
                                                                                                                                              setLoading(false);
                                                                                                                                                    return;
                                                                                                                                                        }

                                                                                                                                                            router.push("/dashboard");
                                                                                                                                                              };

                                                                                                                                                                return (
                                                                                                                                                                    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">
                                                                                                                                                                          <div className="w-full max-w-md bg-white rounded-xl shadow p-8">
                                                                                                                                                                                  <h1 className="text-2xl font-semibold mb-2">
                                                                                                                                                                                            Complete your profile
                                                                                                                                                                                                    </h1>
                                                                                                                                                                                                            <p className="text-gray-600 mb-6">
                                                                                                                                                                                                                      This information will appear on your public profile.
                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                      <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                            <label className="block text-sm font-medium mb-1">
                                                                                                                                                                                                                                                                          Full name
                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                            value={fullName}
                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setFullName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                        className="w-full border rounded-lg px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Your name"
                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                Short bio
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={bio}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setBio(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full border rounded-lg px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="What do you stand for"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-sm font-medium mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Website (optional)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="url"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={website}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setWebsite(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full border rounded-lg px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="https://example.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-red-600 text-sm">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full bg-blue-600 text-white rounded-lg py-2 font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? "Saving..." : "Continue"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
