"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { useRouter } from "next/navigation";

export default function EditProfilePage() {
  const router = useRouter();

    const [username, setUsername] = useState("");
      const [displayName, setDisplayName] = useState("");
        const [loading, setLoading] = useState(true);
          const [saving, setSaving] = useState(false);
            const [error, setError] = useState<string | null>(null);

              useEffect(() => {
                  const loadProfile = async () => {
                        const {
                                data: { user },
                                      } = await supabase.auth.getUser();

                                            if (!user) {
                                                    router.push("/login");
                                                            return;
                                                                  }

                                                                        const { data, error } = await supabase
                                                                                .from("profiles")
                                                                                        .select("username, display_name")
                                                                                                .eq("user_id", user.id)
                                                                                                        .single();

                                                                                                              if (error) {
                                                                                                                      setError(error.message);
                                                                                                                            } else if (data) {
                                                                                                                                    setUsername(data.username || "");
                                                                                                                                            setDisplayName(data.display_name || "");
                                                                                                                                                  }

                                                                                                                                                        setLoading(false);
                                                                                                                                                            };

                                                                                                                                                                loadProfile();
                                                                                                                                                                  }, [router]);

                                                                                                                                                                    const handleSave = async () => {
                                                                                                                                                                        setSaving(true);
                                                                                                                                                                            setError(null);

                                                                                                                                                                                const {
                                                                                                                                                                                      data: { user },
                                                                                                                                                                                          } = await supabase.auth.getUser();

                                                                                                                                                                                              if (!user) {
                                                                                                                                                                                                    setError("Not authenticated");
                                                                                                                                                                                                          setSaving(false);
                                                                                                                                                                                                                return;
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        const { error } = await supabase
                                                                                                                                                                                                                              .from("profiles")
                                                                                                                                                                                                                                    .update({
                                                                                                                                                                                                                                            username,
                                                                                                                                                                                                                                                    display_name: displayName,
                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                .eq("user_id", user.id);

                                                                                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                                                                                          setError(error.message);
                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                    router.push("/dashboard");
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                            setSaving(false);
                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                if (loading) return <div style={{ padding: 24 }}>Loading...</div>;

                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                      <div style={{ padding: 24, maxWidth: 500 }}>
                                                                                                                                                                                                                                                                                                            <h1>Edit Profile</h1>

                                                                                                                                                                                                                                                                                                                  {error && (
                                                                                                                                                                                                                                                                                                                          <p style={{ color: "red", marginBottom: 16 }}>{error}</p>
                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                      <div style={{ marginBottom: 16 }}>
                                                                                                                                                                                                                                                                                                                                              <label>Username</label>
                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                value={username}
                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                            padding: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ marginBottom: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label>Display Name</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={displayName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setDisplayName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleSave}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={saving}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "10px 16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: "black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {saving ? "Saving..." : "Save Changes"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }