"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function SignupPage() {
  const supabase = createClient();

    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [username, setUsername] = useState("");
          const [loading, setLoading] = useState(false);

            const handleSignup = async (e: React.FormEvent) => {
                e.preventDefault();

                    if (!email || !password || !username) {
                          alert("Please fill all fields");
                                return;
                                    }

                                        setLoading(true);

                                            try {
                                                  // Step 1: create auth user
                                                        const { data, error } = await supabase.auth.signUp({
                                                                email,
                                                                        password,
                                                                              });

                                                                                    if (error) {
                                                                                            alert(error.message);
                                                                                                    setLoading(false);
                                                                                                            return;
                                                                                                                  }

                                                                                                                        if (!data.user) {
                                                                                                                                alert("Signup failed");
                                                                                                                                        setLoading(false);
                                                                                                                                                return;
                                                                                                                                                      }

                                                                                                                                                            // Step 2: insert profile with username
                                                                                                                                                                  const { error: profileError } = await supabase
                                                                                                                                                                          .from("profiles")
                                                                                                                                                                                  .insert({
                                                                                                                                                                                            user_id: data.user.id,
                                                                                                                                                                                                      username: username.toLowerCase(),
                                                                                                                                                                                                                display_name: username,
                                                                                                                                                                                                                        });

                                                                                                                                                                                                                              if (profileError) {
                                                                                                                                                                                                                                      alert(profileError.message);
                                                                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                  // Step 3: redirect to dashboard
                                                                                                                                                                                                                                                                        window.location.href = "/dashboard";

                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                  alert("Unexpected error occurred");
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                  <div style={{ padding: "40px", maxWidth: "400px", margin: "auto" }}>
                                                                                                                                                                                                                                                                                                        <h1>Create your account</h1>

                                                                                                                                                                                                                                                                                                              <form onSubmit={handleSignup}>

                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                          placeholder="Username"
                                                                                                                                                                                                                                                                                                                                                    value={username}
                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                  style={{ width: "100%", padding: "10px", marginBottom: "10px" }}
                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                            type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Email"
                                                                                                                                                                                                                                                                                                                                                                                                                                value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ width: "100%", padding: "10px", marginBottom: "10px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ width: "100%", padding: "10px", marginBottom: "10px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "#2563eb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? "Creating account..." : "Sign up"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }