"use client";

import { useState } from "react";
import { supabase } from "@/lib/supabaseClient";

export default function SignupPage() {
  const [username, setUsername] = useState("");
    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [error, setError] = useState("");
          const [loading, setLoading] = useState(false);

            const handleSignup = async () => {
                setError("");

                    if (!username || !email || !password) {
                          setError("Please fill all details");
                                return;
                                    }

                                        setLoading(true);

                                            const { error } = await supabase.auth.signUp({
                                                  email,
                                                        password,
                                                              options: {
                                                                      data: { username },
                                                                            },
                                                                                });

                                                                                    setLoading(false);

                                                                                        if (error) {
                                                                                              setError(error.message);
                                                                                                    return;
                                                                                                        }

                                                                                                            alert("Signup successful. Check your email if confirmation is enabled.");
                                                                                                              };

                                                                                                                return (
                                                                                                                    <div
                                                                                                                          style={{
                                                                                                                                  minHeight: "100vh",
                                                                                                                                          display: "flex",
                                                                                                                                                  alignItems: "center",
                                                                                                                                                          justifyContent: "center",
                                                                                                                                                                  background: "#f5f7fb",
                                                                                                                                                                          padding: "16px",
                                                                                                                                                                                }}
                                                                                                                                                                                    >
                                                                                                                                                                                          <div
                                                                                                                                                                                                  style={{
                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                      maxWidth: "420px",
                                                                                                                                                                                                                                background: "#fff",
                                                                                                                                                                                                                                          padding: "32px",
                                                                                                                                                                                                                                                    borderRadius: "12px",
                                                                                                                                                                                                                                                              boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                    <h1 style={{ fontSize: "26px", marginBottom: "8px" }}>
                                                                                                                                                                                                                                                                                              Create your account
                                                                                                                                                                                                                                                                                                      </h1>

                                                                                                                                                                                                                                                                                                              <p style={{ color: "#666", marginBottom: "24px" }}>
                                                                                                                                                                                                                                                                                                                        Your profile becomes a place where intentions are stated clearly and publicly.
                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                        <label>Username</label>
                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                          value={username}
                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                              placeholder="yourname"
                                                                                                                                                                                                                                                                                                                                                                                        style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                        <label>Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                          value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="you@example.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Minimum 6 characters"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ color: "red", marginBottom: "12px" }}>{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleSignup}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "#2563eb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? "Creating account..." : "Create account"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ marginTop: "16px", fontSize: "14px", color: "#777" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                By continuing, you agree to keep commitments honest and visible.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const inputStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid #ddd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };