"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";

export default function SignupPage() {
  const supabase = createClientComponentClient();
    const router = useRouter();

      const [username, setUsername] = useState("");
        const [email, setEmail] = useState("");
          const [password, setPassword] = useState("");
            const [error, setError] = useState("");
              const [loading, setLoading] = useState(false);

                const handleSignup = async () => {
                    setError("");
                        setLoading(true);

                            try {
                                  // Create auth user
                                        const { data, error: authError } = await supabase.auth.signUp({
                                                email,
                                                        password,
                                                              });

                                                                    if (authError) {
                                                                            if (authError.message.includes("already registered")) {
                                                                                      setError("Email already exists. Please use another email.");
                                                                                              } else {
                                                                                                        setError(authError.message);
                                                                                                                }
                                                                                                                        setLoading(false);
                                                                                                                                return;
                                                                                                                                      }

                                                                                                                                            const user = data.user;

                                                                                                                                                  if (!user) {
                                                                                                                                                          setError("Signup failed. Try again.");
                                                                                                                                                                  setLoading(false);
                                                                                                                                                                          return;
                                                                                                                                                                                }

                                                                                                                                                                                      // Insert profile using correct column name: id
                                                                                                                                                                                            const { error: profileError } = await supabase
                                                                                                                                                                                                    .from("profiles")
                                                                                                                                                                                                            .insert({
                                                                                                                                                                                                                      id: user.id,
                                                                                                                                                                                                                                username: username,
                                                                                                                                                                                                                                          display_name: username,
                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                        if (profileError) {
                                                                                                                                                                                                                                                                if (profileError.message.includes("profiles_username_key")) {
                                                                                                                                                                                                                                                                          setError("Username already exists. Please choose another username.");
                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                            setError("Database error saving new user.");
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                            setLoading(false);
                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                // SUCCESS → redirect
                                                                                                                                                                                                                                                                                                                                      router.push("/dashboard");

                                                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                                                                setError("Unexpected error occurred.");
                                                                                                                                                                                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                  <div style={{
                                                                                                                                                                                                                                                                                                                                                                        maxWidth: 400,
                                                                                                                                                                                                                                                                                                                                                                              margin: "100px auto",
                                                                                                                                                                                                                                                                                                                                                                                    padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid #ddd",
                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 8
                                                                                                                                                                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                                                                                                                                                                          <h2>Create your account</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Username"
                                                                                                                                                                                                                                                                                                                                                                                                                                value={username}
                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ width: "100%", padding: 10, marginTop: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: "100%", padding: 10, marginTop: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ width: "100%", padding: 10, marginTop: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ color: "red", marginTop: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleSignup}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: "#2563eb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? "Creating account..." : "Create account"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }