"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";

type Profile = {
  id: string;
    username: string;
      full_name: string | null;
        bio: string | null;
          website: string | null;
            profile_type: "individual" | "company" | null;
              title: string | null;
              };

              export default function DashboardPage() {
                const router = useRouter();
                  const [loading, setLoading] = useState(true);
                    const [profile, setProfile] = useState<Profile | null>(null);

                      useEffect(() => {
                          const loadDashboard = async () => {
                                const {
                                        data: { user },
                                              } = await supabase.auth.getUser();

                                                    if (!user) {
                                                            router.replace("/signup");
                                                                    return;
                                                                          }

                                                                                const { data } = await supabase
                                                                                        .from("profiles")
                                                                                                .select("*")
                                                                                                        .eq("id", user.id)
                                                                                                                .single();

                                                                                                                      setProfile(data);
                                                                                                                            setLoading(false);
                                                                                                                                };

                                                                                                                                    loadDashboard();
                                                                                                                                      }, [router]);

                                                                                                                                        if (loading) {
                                                                                                                                            return (
                                                                                                                                                  <div className="min-h-screen flex items-center justify-center">
                                                                                                                                                          Loading dashboard…
                                                                                                                                                                </div>
                                                                                                                                                                    );
                                                                                                                                                                      }

                                                                                                                                                                        if (!profile) {
                                                                                                                                                                            return (
                                                                                                                                                                                  <div className="min-h-screen flex items-center justify-center">
                                                                                                                                                                                          Profile not found.
                                                                                                                                                                                                </div>
                                                                                                                                                                                                    );
                                                                                                                                                                                                      }

                                                                                                                                                                                                        const profileComplete =
                                                                                                                                                                                                            profile.full_name && profile.bio && profile.profile_type;

                                                                                                                                                                                                              return (
                                                                                                                                                                                                                  <main className="min-h-screen bg-gray-50 px-4 py-10">
                                                                                                                                                                                                                        <div className="mx-auto max-w-3xl space-y-8">
                                                                                                                                                                                                                                {/* Profile Card */}
                                                                                                                                                                                                                                        <div className="rounded-xl bg-white p-6 shadow">
                                                                                                                                                                                                                                                  <h1 className="text-2xl font-semibold">Dashboard</h1>

                                                                                                                                                                                                                                                            <div className="mt-4 space-y-2 text-sm text-gray-700">
                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                      <strong>Username:</strong> @{profile.username}
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                            <strong>Name:</strong>{" "}
                                                                                                                                                                                                                                                                                                                                          {profile.full_name || "Not set"}
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                <strong>Status:</strong>{" "}
                                                                                                                                                                                                                                                                                                                                                                                              {profileComplete ? "Public" : "Incomplete"}
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                              {!profileComplete && (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-4 rounded-md bg-yellow-50 p-3 text-sm text-yellow-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Complete your profile to make it public.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => router.push("/onboarding")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="mt-5 rounded-md bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Edit profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Commitments Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="rounded-xl bg-white p-6 shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-xl font-semibold">Commitments</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="mt-2 text-sm text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        You haven’t stated any commitments yet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="mt-4 rounded-md bg-gray-300 px-4 py-2 text-gray-600 cursor-not-allowed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Create your first commitment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }