"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { useRouter } from "next/navigation";

export default function Dashboard() {
  const router = useRouter();

    const [user, setUser] = useState(null);
      const [profile, setProfile] = useState(null);
        const [credits, setCredits] = useState(0);
          const [commitments, setCommitments] = useState([]);

            const [title, setTitle] = useState("");
              const [loading, setLoading] = useState(false);
                const [message, setMessage] = useState("");

                  useEffect(() => {
                      loadAll();
                        }, []);

                          async function loadAll() {
                              const {
                                    data: { user },
                                        } = await supabase.auth.getUser();

                                            if (!user) {
                                                  router.push("/login");
                                                        return;
                                                            }

                                                                setUser(user);

                                                                    // profile
                                                                        const { data: profileData } = await supabase
                                                                              .from("profiles")
                                                                                    .select("*")
                                                                                          .eq("id", user.id)
                                                                                                .single();

                                                                                                    setProfile(profileData);

                                                                                                        // credits
                                                                                                            const { data: creditData } = await supabase
                                                                                                                  .from("credits")
                                                                                                                        .select("*")
                                                                                                                              .eq("user_id", user.id)
                                                                                                                                    .single();

                                                                                                                                        if (creditData) {
                                                                                                                                              setCredits(creditData.credits_remaining);
                                                                                                                                                  }

                                                                                                                                                      // commitments
                                                                                                                                                          const { data: commitmentData } = await supabase
                                                                                                                                                                .from("commitments")
                                                                                                                                                                      .select("*")
                                                                                                                                                                            .eq("user_id", user.id)
                                                                                                                                                                                  .order("created_at", { ascending: false });

                                                                                                                                                                                      setCommitments(commitmentData || []);
                                                                                                                                                                                        }

                                                                                                                                                                                          async function createCommitment() {
                                                                                                                                                                                              setMessage("");

                                                                                                                                                                                                  if (!title.trim()) {
                                                                                                                                                                                                        setMessage("Enter commitment");
                                                                                                                                                                                                              return;
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                      if (title.length > 200) {
                                                                                                                                                                                                                            setMessage("Max 200 characters");
                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                          if (credits <= 0) {
                                                                                                                                                                                                                                                setMessage("No credits remaining");
                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                              setLoading(true);

                                                                                                                                                                                                                                                                  const {
                                                                                                                                                                                                                                                                        data: { user },
                                                                                                                                                                                                                                                                            } = await supabase.auth.getUser();

                                                                                                                                                                                                                                                                                // insert commitment
                                                                                                                                                                                                                                                                                    const { error } = await supabase.from("commitments").insert({
                                                                                                                                                                                                                                                                                          user_id: user.id,
                                                                                                                                                                                                                                                                                                title: title,
                                                                                                                                                                                                                                                                                                      status: "active",
                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                              if (error) {
                                                                                                                                                                                                                                                                                                                    setMessage(error.message);
                                                                                                                                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                        // deduct credit
                                                                                                                                                                                                                                                                                                                                            await supabase
                                                                                                                                                                                                                                                                                                                                                  .from("credits")
                                                                                                                                                                                                                                                                                                                                                        .update({
                                                                                                                                                                                                                                                                                                                                                                credits_used: supabase.rpc ? undefined : undefined,
                                                                                                                                                                                                                                                                                                                                                                        credits_remaining: credits - 1,
                                                                                                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                                                                                                    .eq("user_id", user.id);

                                                                                                                                                                                                                                                                                                                                                                                        setTitle("");
                                                                                                                                                                                                                                                                                                                                                                                            setMessage("Commitment created");
                                                                                                                                                                                                                                                                                                                                                                                                setLoading(false);

                                                                                                                                                                                                                                                                                                                                                                                                    loadAll();
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                        async function logout() {
                                                                                                                                                                                                                                                                                                                                                                                                            await supabase.auth.signOut();
                                                                                                                                                                                                                                                                                                                                                                                                                router.push("/login");
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                    if (!profile) return <div>Loading...</div>;

                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ padding: 20 }}>

                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Dashboard</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                              Public profile:{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href={`/u/${profile.username}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                /u/{profile.username}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>Credits remaining: {credits}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>Create Commitment</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setTitle(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Enter your commitment"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      maxLength={200}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={createCommitment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? "Creating..." : "Create"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>{message}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>Your Commitments</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {commitments.length === 0 && <p>No commitments yet</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {commitments.map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={c.id} style={{ marginTop: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {c.title} — {c.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={logout}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }