"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";

export default function Dashboard() {
  const [loading, setLoading] = useState(true);
    const [profile, setProfile] = useState<any>(null);
      const [displayName, setDisplayName] = useState("");
        const [bio, setBio] = useState("");
          const [website, setWebsite] = useState("");

            useEffect(() => {
                loadProfile();
                  }, []);

                    async function loadProfile() {
                        const {
                              data: { user },
                                  } = await supabase.auth.getUser();

                                      if (!user) {
                                            window.location.href = "/login";
                                                  return;
                                                      }

                                                          // Try get profile
                                                              let { data, error } = await supabase
                                                                    .from("profiles")
                                                                          .select("*")
                                                                                .eq("id", user.id)
                                                                                      .single();

                                                                                          // If profile does not exist → create it automatically
                                                                                              if (!data) {
                                                                                                    const username =
                                                                                                            user.email?.split("@")[0].toLowerCase().replace(/[^a-z0-9]/g, "") +
                                                                                                                    Math.floor(Math.random() * 1000);

                                                                                                                          await supabase.from("profiles").insert({
                                                                                                                                  id: user.id,
                                                                                                                                          username: username,
                                                                                                                                                  display_name: "",
                                                                                                                                                          bio: "",
                                                                                                                                                                  website: "",
                                                                                                                                                                        });

                                                                                                                                                                              const { data: newProfile } = await supabase
                                                                                                                                                                                      .from("profiles")
                                                                                                                                                                                              .select("*")
                                                                                                                                                                                                      .eq("id", user.id)
                                                                                                                                                                                                              .single();

                                                                                                                                                                                                                    data = newProfile;
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                            setProfile(data);
                                                                                                                                                                                                                                setDisplayName(data.display_name || "");
                                                                                                                                                                                                                                    setBio(data.bio || "");
                                                                                                                                                                                                                                        setWebsite(data.website || "");
                                                                                                                                                                                                                                            setLoading(false);
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                async function saveProfile() {
                                                                                                                                                                                                                                                    const {
                                                                                                                                                                                                                                                          data: { user },
                                                                                                                                                                                                                                                              } = await supabase.auth.getUser();

                                                                                                                                                                                                                                                                  const { error } = await supabase.from("profiles").update({
                                                                                                                                                                                                                                                                        display_name: displayName,
                                                                                                                                                                                                                                                                              bio: bio,
                                                                                                                                                                                                                                                                                    website: website,
                                                                                                                                                                                                                                                                                        }).eq("id", user?.id);

                                                                                                                                                                                                                                                                                            if (!error) alert("Profile saved");
                                                                                                                                                                                                                                                                                                else alert("Error saving profile");
                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                    async function logout() {
                                                                                                                                                                                                                                                                                                        await supabase.auth.signOut();
                                                                                                                                                                                                                                                                                                            window.location.href = "/";
                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                if (loading) return <div style={{ padding: 40 }}>Loading...</div>;

                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                      <div style={{ padding: 40 }}>
                                                                                                                                                                                                                                                                                                                            <h1>Dashboard</h1>

                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                          Public profile: <br />
                                                                                                                                                                                                                                                                                                                                                  <a href={`/u/${profile.username}`}>
                                                                                                                                                                                                                                                                                                                                                            /u/{profile.username}
                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Full name"
                                                                                                                                                                                                                                                                                                                                                                                                value={displayName}
                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setDisplayName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                style={{ display: "block", marginBottom: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Bio"
                                                                                                                                                                                                                                                                                                                                                                                                                                            value={bio}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setBio(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ display: "block", marginBottom: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Website"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={website}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setWebsite(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ display: "block", marginBottom: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={saveProfile}>Save Profile</button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <br /><br />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={logout}>Logout</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }<a href="/dashboard/create">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button>Create Commitment</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>