"use client";

import { useState, useEffect } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

export default function CreateCommitmentPage() {
  const supabase = createClient();
    const router = useRouter();

      const [userId, setUserId] = useState<string | null>(null);
        const [credits, setCredits] = useState<number>(0);

          const [text, setText] = useState("");
            const [durationType, setDurationType] = useState("30_days");
              const [startDate, setStartDate] = useState("");
                const [endDate, setEndDate] = useState("");
                  const [visibility, setVisibility] = useState("public");

                    const [loading, setLoading] = useState(false);
                      const [error, setError] = useState("");

                        useEffect(() => {
                            loadUser();
                              }, []);

                                async function loadUser() {
                                    const {
                                          data: { user },
                                              } = await supabase.auth.getUser();

                                                  if (!user) {
                                                        router.push("/login");
                                                              return;
                                                                  }

                                                                      setUserId(user.id);

                                                                          const { data } = await supabase
                                                                                .from("credits")
                                                                                      .select("credits_remaining")
                                                                                            .eq("user_id", user.id)
                                                                                                  .single();

                                                                                                      if (data) setCredits(data.credits_remaining);
                                                                                                        }

                                                                                                          async function handleCreate() {
                                                                                                              setError("");

                                                                                                                  if (!text) {
                                                                                                                        setError("Commitment text required");
                                                                                                                              return;
                                                                                                                                  }

                                                                                                                                      if (!startDate || !endDate) {
                                                                                                                                            setError("Start and End dates required");
                                                                                                                                                  return;
                                                                                                                                                      }

                                                                                                                                                          if (credits <= 0) {
                                                                                                                                                                setError("No credits remaining");
                                                                                                                                                                      return;
                                                                                                                                                                          }

                                                                                                                                                                              setLoading(true);

                                                                                                                                                                                  try {
                                                                                                                                                                                        const { error: insertError } = await supabase
                                                                                                                                                                                                .from("commitments")
                                                                                                                                                                                                        .insert({
                                                                                                                                                                                                                  user_id: userId,
                                                                                                                                                                                                                            text: text,
                                                                                                                                                                                                                                      status: "active",
                                                                                                                                                                                                                                                duration_type: durationType,
                                                                                                                                                                                                                                                          start_date: startDate,
                                                                                                                                                                                                                                                                    end_date: endDate,
                                                                                                                                                                                                                                                                              visibility: visibility,
                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                            if (insertError) throw insertError;

                                                                                                                                                                                                                                                                                                  await supabase.rpc("consume_credit");

                                                                                                                                                                                                                                                                                                        router.push("/dashboard");

                                                                                                                                                                                                                                                                                                            } catch (err: any) {
                                                                                                                                                                                                                                                                                                                  setError(err.message);
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                  <div style={{ maxWidth: 500, margin: "40px auto" }}>

                                                                                                                                                                                                                                                                                                                                        <h1>Create Commitment</h1>

                                                                                                                                                                                                                                                                                                                                              <p>Credits remaining: {credits}</p>

                                                                                                                                                                                                                                                                                                                                                    <textarea
                                                                                                                                                                                                                                                                                                                                                            placeholder="I will wake up at 6am daily"
                                                                                                                                                                                                                                                                                                                                                                    maxLength={200}
                                                                                                                                                                                                                                                                                                                                                                            value={text}
                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setText(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: "100%", height: 100, marginBottom: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                        <label>Duration</label>
                                                                                                                                                                                                                                                                                                                                                                                                              <select
                                                                                                                                                                                                                                                                                                                                                                                                                      value={durationType}
                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setDurationType(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: "100%", marginBottom: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="7_days">7 Days</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="14_days">14 Days</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="21_days">21 Days</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="30_days">30 Days</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="90_days">90 Days</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="180_days">180 Days</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="365_days">365 Days</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="custom">Custom</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>Start Date</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="date"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={startDate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setStartDate(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ width: "100%", marginBottom: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label>End Date</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="date"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={endDate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setEndDate(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ width: "100%", marginBottom: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>Visibility</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={visibility}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setVisibility(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ width: "100%", marginBottom: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="public">Public</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="private">Private</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ color: "red" }}>{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleCreate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: "#2563eb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "Creating..." : "Create Commitment"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }